-- Multi-tenancy foundation: a tenant scopes teams/periods/goals/users.
-- A single-install OSS box uses one default tenant (#1); existing data backfills into it.
CREATE TABLE tenants (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug       TEXT NOT NULL UNIQUE,
    name       TEXT NOT NULL,
    status     TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'suspended')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    deleted_at TIMESTAMPTZ
);

-- Default tenant for OSS single-install and as backfill target for existing rows.
INSERT INTO tenants (id, slug, name) OVERRIDING SYSTEM VALUE
VALUES (1, 'default', 'Default');

-- Advance the identity sequence past the manually inserted id=1, otherwise the next
-- auto-generated id would collide with the default tenant.
SELECT setval(pg_get_serial_sequence('tenants', 'id'), (SELECT max(id) FROM tenants));
