-- Membership maps a global user into N tenants with a per-tenant role.
-- is_system_admin is the instance superadmin (tenant-less); split out of legacy is_admin.
ALTER TABLE users ADD COLUMN is_system_admin BOOLEAN NOT NULL DEFAULT false;

CREATE TABLE memberships (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    tenant_id          BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    role               TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    status             TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'requested')),
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    UNIQUE (user_id, tenant_id)
);

-- Backfill: every existing user becomes an active member of the default tenant.
-- Legacy admins become tenant admins AND instance system admins (they were the operator).
INSERT INTO memberships (user_id, tenant_id, role, status)
SELECT id, 1, CASE WHEN is_admin THEN 'admin' ELSE 'user' END, 'active'
FROM users;

UPDATE users SET is_system_admin = true WHERE is_admin = true;
