-- Token-based invitations (claimed by redeeming the link while logged in, not by email-match).
CREATE TABLE tenant_invitations (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id          BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    email              TEXT NOT NULL,
    role               TEXT NOT NULL DEFAULT 'user' CHECK (role IN ('user', 'admin')),
    token_hash         TEXT NOT NULL,
    status             TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'claimed', 'revoked')),
    created_by_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT now(),
    expires_at         TIMESTAMPTZ
);
CREATE INDEX idx_tenant_invitations_tenant ON tenant_invitations(tenant_id);

-- Session remembers which tenant it is currently viewing.
ALTER TABLE auth_sessions ADD COLUMN active_tenant_id BIGINT REFERENCES tenants(id);

-- Period name is unique per tenant, not globally (the inline UNIQUE was named periods_name_key).
ALTER TABLE periods DROP CONSTRAINT IF EXISTS periods_name_key;
ALTER TABLE periods ADD CONSTRAINT periods_tenant_name_key UNIQUE (tenant_id, name);
