-- Activity log: append-only journal of OKR mutations (progress, composition, status, discussion).
CREATE TABLE activity_events (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    actor_user_id BIGINT NOT NULL REFERENCES users(id),
    category      TEXT NOT NULL CHECK (category IN ('progress','composition','status','discussion')),
    action        TEXT NOT NULL,
    team_id       BIGINT REFERENCES teams(id) ON DELETE SET NULL,
    period_id     BIGINT REFERENCES periods(id) ON DELETE SET NULL,
    goal_id       BIGINT,
    kr_id         BIGINT,
    comment_id    BIGINT,
    entity_title  TEXT NOT NULL DEFAULT '',
    payload_json  JSONB NOT NULL DEFAULT '{}',
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
-- goal_id/kr_id/comment_id are intentionally NOT foreign keys: the journal is append-only and
-- must survive deletion of the referenced entity (entity_title keeps the row readable).
CREATE INDEX idx_activity_events_tenant_created ON activity_events(tenant_id, created_at DESC, id DESC);
CREATE INDEX idx_activity_events_tenant_period  ON activity_events(tenant_id, period_id, created_at DESC);
CREATE INDEX idx_activity_events_tenant_team    ON activity_events(tenant_id, team_id, created_at DESC);
CREATE INDEX idx_activity_events_tenant_actor   ON activity_events(tenant_id, actor_user_id);
CREATE INDEX idx_activity_events_goal           ON activity_events(goal_id);
