-- Daily materialised progress per team per period, for the period progress chart.
CREATE TABLE team_period_progress_snapshots (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_id     BIGINT NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    period_id     BIGINT NOT NULL REFERENCES periods(id) ON DELETE CASCADE,
    team_id       BIGINT NOT NULL REFERENCES teams(id) ON DELETE CASCADE,
    snapshot_date DATE   NOT NULL,
    progress      INTEGER NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (tenant_id, period_id, team_id, snapshot_date)
);
CREATE INDEX idx_tpps_tenant_period_date ON team_period_progress_snapshots(tenant_id, period_id, snapshot_date);
