--
-- PostgreSQL database dump
--

\restrict zArFcmtINrh3EjUASKPkJcZoW2PQoRdheicuSkAzTJDS2e3vm7bIODQHZ35PTZY

-- Dumped from database version 15.18 (Debian 15.18-1.pgdg13+1)
-- Dumped by pg_dump version 15.18 (Debian 15.18-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner: -
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: activity_events; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.activity_events (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    actor_user_id bigint NOT NULL,
    category text NOT NULL,
    action text NOT NULL,
    team_id bigint,
    period_id bigint,
    goal_id bigint,
    kr_id bigint,
    comment_id bigint,
    entity_title text DEFAULT ''::text NOT NULL,
    payload_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT activity_events_category_check CHECK ((category = ANY (ARRAY['progress'::text, 'composition'::text, 'status'::text, 'discussion'::text])))
);


--
-- Name: activity_events_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.activity_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.activity_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_sessions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_sessions (
    id text NOT NULL,
    user_id bigint NOT NULL,
    provider text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    last_seen_at timestamp with time zone DEFAULT now() NOT NULL,
    user_agent text,
    ip text,
    active_tenant_id bigint
);


--
-- Name: goal_comments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.goal_comments (
    id integer NOT NULL,
    goal_id integer NOT NULL,
    text text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    author_user_id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    resolved_at timestamp with time zone,
    resolved_by_user_id bigint,
    parent_id bigint
);


--
-- Name: goal_comments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.goal_comments_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: goal_comments_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.goal_comments_id_seq OWNED BY public.goal_comments.id;


--
-- Name: goal_links; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.goal_links (
    tenant_id bigint NOT NULL,
    child_goal_id bigint NOT NULL,
    parent_goal_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT goal_links_no_self CHECK ((child_goal_id <> parent_goal_id))
);


--
-- Name: goal_shares; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.goal_shares (
    goal_id integer NOT NULL,
    team_id integer NOT NULL,
    weight integer NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    tenant_id bigint NOT NULL,
    CONSTRAINT goal_shares_weight_check CHECK (((weight >= 0) AND (weight <= 100)))
);


--
-- Name: goals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.goals (
    id integer NOT NULL,
    team_id integer NOT NULL,
    title text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    priority text NOT NULL,
    weight integer NOT NULL,
    work_type text NOT NULL,
    focus_type text NOT NULL,
    owner_text text DEFAULT ''::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    period_id integer NOT NULL,
    owner_udids uuid[],
    tenant_id bigint NOT NULL,
    CONSTRAINT goals_weight_check CHECK (((weight >= 0) AND (weight <= 100)))
);


--
-- Name: goals_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.goals_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: goals_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.goals_id_seq OWNED BY public.goals.id;


--
-- Name: key_result_notes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.key_result_notes (
    key_result_id bigint NOT NULL,
    text text NOT NULL,
    author_user_id bigint NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    tenant_id bigint NOT NULL
);


--
-- Name: key_results; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.key_results (
    id integer NOT NULL,
    goal_id integer NOT NULL,
    title text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    weight integer NOT NULL,
    kind text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    progress_updated_at timestamp with time zone,
    unit text,
    start_value double precision,
    target_value double precision,
    current_value double precision,
    checkpoints jsonb,
    zeroing_criteria text DEFAULT ''::text NOT NULL,
    tenant_id bigint NOT NULL,
    health_status text DEFAULT 'not_started'::text NOT NULL,
    CONSTRAINT key_results_weight_check CHECK (((weight >= 0) AND (weight <= 100)))
);


--
-- Name: key_results_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.key_results_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: key_results_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.key_results_id_seq OWNED BY public.key_results.id;


--
-- Name: kr_boolean_meta; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.kr_boolean_meta (
    key_result_id integer NOT NULL,
    is_done boolean DEFAULT false NOT NULL
);


--
-- Name: kr_project_stages; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.kr_project_stages (
    id integer NOT NULL,
    key_result_id integer NOT NULL,
    title text NOT NULL,
    weight integer NOT NULL,
    is_done boolean DEFAULT false NOT NULL,
    sort_order integer DEFAULT 0 NOT NULL,
    CONSTRAINT kr_project_stages_weight_check CHECK (((weight >= 0) AND (weight <= 100)))
);


--
-- Name: kr_project_stages_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.kr_project_stages_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: kr_project_stages_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.kr_project_stages_id_seq OWNED BY public.kr_project_stages.id;


--
-- Name: memberships; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.memberships (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    role text DEFAULT 'user'::text NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by_user_id bigint,
    CONSTRAINT memberships_role_check CHECK ((role = ANY (ARRAY['user'::text, 'admin'::text]))),
    CONSTRAINT memberships_status_check CHECK ((status = ANY (ARRAY['active'::text, 'requested'::text])))
);


--
-- Name: memberships_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.memberships ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.memberships_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification_channels; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification_channels (
    tenant_id bigint NOT NULL,
    channel text NOT NULL,
    enabled boolean DEFAULT false NOT NULL,
    config_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    secret_enc bytea,
    secret_hint text DEFAULT ''::text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_by_user_id bigint,
    default_on boolean DEFAULT false NOT NULL
);


--
-- Name: notification_identities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification_identities (
    tenant_id bigint NOT NULL,
    user_id bigint NOT NULL,
    channel text NOT NULL,
    external_id text NOT NULL,
    external_username text,
    linked_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: notification_preferences; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification_preferences (
    tenant_id bigint NOT NULL,
    user_id bigint NOT NULL,
    type text NOT NULL,
    enabled boolean DEFAULT true NOT NULL,
    scope text,
    channel_overrides jsonb DEFAULT '{}'::jsonb NOT NULL,
    CONSTRAINT notification_preferences_scope CHECK (((scope IS NULL) OR (scope = ANY (ARRAY['own'::text, 'own_and_children'::text, 'subtree'::text])))),
    CONSTRAINT notification_preferences_type CHECK ((type = ANY (ARRAY['goal_comment'::text, 'my_comment_resolved'::text, 'goal_changed'::text, 'kr_progress'::text, 'access_requested'::text])))
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    user_id bigint NOT NULL,
    type text NOT NULL,
    kind text NOT NULL,
    actor_user_id bigint NOT NULL,
    team_id bigint,
    period_id bigint,
    goal_id bigint,
    kr_id bigint,
    comment_id bigint,
    entity_title text DEFAULT ''::text NOT NULL,
    payload_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    coalesce_key text NOT NULL,
    coalesce_count integer DEFAULT 1 NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    read_at timestamp with time zone,
    CONSTRAINT notifications_type CHECK ((type = ANY (ARRAY['goal_comment'::text, 'my_comment_resolved'::text, 'goal_changed'::text, 'kr_progress'::text, 'access_requested'::text])))
);


--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: notifications_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.notifications_id_seq OWNED BY public.notifications.id;


--
-- Name: periods; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.periods (
    id integer NOT NULL,
    name text NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    tenant_id bigint NOT NULL,
    archived_at timestamp with time zone
);


--
-- Name: periods_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.periods_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: periods_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.periods_id_seq OWNED BY public.periods.id;


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version bigint NOT NULL,
    dirty boolean NOT NULL
);


--
-- Name: system_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.system_settings (
    key text NOT NULL,
    value_json jsonb DEFAULT 'null'::jsonb NOT NULL
);


--
-- Name: team_period_progress_snapshots; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.team_period_progress_snapshots (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    period_id bigint NOT NULL,
    team_id bigint NOT NULL,
    snapshot_date date NOT NULL,
    progress integer NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);


--
-- Name: team_period_progress_snapshots_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.team_period_progress_snapshots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_period_progress_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: team_period_statuses; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.team_period_statuses (
    team_id integer NOT NULL,
    period_id integer NOT NULL,
    status text NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    tenant_id bigint NOT NULL
);


--
-- Name: teams; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teams (
    id integer NOT NULL,
    name text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    team_type text DEFAULT 'team'::text NOT NULL,
    parent_id integer,
    lead text DEFAULT ''::text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    deleted_at timestamp with time zone,
    lead_udid uuid,
    tenant_id bigint NOT NULL,
    CONSTRAINT teams_team_type_check CHECK ((team_type = ANY (ARRAY['department'::text, 'cluster'::text, 'unit'::text, 'group'::text, 'team'::text, 'squad'::text, 'employee'::text])))
);


--
-- Name: teams_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.teams_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: teams_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.teams_id_seq OWNED BY public.teams.id;


--
-- Name: tenant_invitations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tenant_invitations (
    id bigint NOT NULL,
    tenant_id bigint NOT NULL,
    email text,
    role text DEFAULT 'user'::text NOT NULL,
    token_hash text NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    created_by_user_id bigint,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    expires_at timestamp with time zone,
    max_uses integer,
    use_count integer DEFAULT 0 NOT NULL,
    CONSTRAINT tenant_invitations_role_check CHECK ((role = ANY (ARRAY['user'::text, 'admin'::text]))),
    CONSTRAINT tenant_invitations_status_check CHECK ((status = ANY (ARRAY['pending'::text, 'claimed'::text, 'revoked'::text])))
);


--
-- Name: tenant_invitations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tenant_invitations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tenant_invitations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tenant_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tenant_settings (
    tenant_id bigint NOT NULL,
    key text NOT NULL,
    value_json jsonb NOT NULL
);


--
-- Name: tenants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.tenants (
    id bigint NOT NULL,
    slug text NOT NULL,
    name text NOT NULL,
    status text DEFAULT 'active'::text NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    deleted_at timestamp with time zone,
    CONSTRAINT tenants_status_check CHECK ((status = ANY (ARRAY['active'::text, 'suspended'::text])))
);


--
-- Name: tenants_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.tenants ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tenants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_hierarchy_grants; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_hierarchy_grants (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    team_id bigint NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    created_by_user_id bigint NOT NULL,
    tenant_id bigint NOT NULL
);


--
-- Name: user_hierarchy_grants_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_hierarchy_grants_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_hierarchy_grants_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.user_hierarchy_grants_id_seq OWNED BY public.user_hierarchy_grants.id;


--
-- Name: user_settings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_settings (
    user_id bigint NOT NULL,
    key text NOT NULL,
    value_json jsonb NOT NULL
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    provider_subject_key text NOT NULL,
    provider text NOT NULL,
    subject text NOT NULL,
    display_name text NOT NULL,
    avatar_url text DEFAULT ''::text NOT NULL,
    email text,
    attributes_json jsonb DEFAULT '{}'::jsonb NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    last_login_at timestamp with time zone DEFAULT now() NOT NULL,
    udid uuid DEFAULT gen_random_uuid() NOT NULL,
    is_system_admin boolean DEFAULT false NOT NULL
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: goal_comments id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goal_comments ALTER COLUMN id SET DEFAULT nextval('public.goal_comments_id_seq'::regclass);


--
-- Name: goals id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals ALTER COLUMN id SET DEFAULT nextval('public.goals_id_seq'::regclass);


--
-- Name: key_results id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.key_results ALTER COLUMN id SET DEFAULT nextval('public.key_results_id_seq'::regclass);


--
-- Name: kr_project_stages id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kr_project_stages ALTER COLUMN id SET DEFAULT nextval('public.kr_project_stages_id_seq'::regclass);


--
-- Name: notifications id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications ALTER COLUMN id SET DEFAULT nextval('public.notifications_id_seq'::regclass);


--
-- Name: periods id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.periods ALTER COLUMN id SET DEFAULT nextval('public.periods_id_seq'::regclass);


--
-- Name: teams id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams ALTER COLUMN id SET DEFAULT nextval('public.teams_id_seq'::regclass);


--
-- Name: user_hierarchy_grants id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_hierarchy_grants ALTER COLUMN id SET DEFAULT nextval('public.user_hierarchy_grants_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Data for Name: activity_events; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.activity_events (id, tenant_id, actor_user_id, category, action, team_id, period_id, goal_id, kr_id, comment_id, entity_title, payload_json, created_at) FROM stdin;
\.


--
-- Data for Name: auth_sessions; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.auth_sessions (id, user_id, provider, created_at, expires_at, last_seen_at, user_agent, ip, active_tenant_id) FROM stdin;
\.


--
-- Data for Name: goal_comments; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.goal_comments (id, goal_id, text, created_at, author_user_id, tenant_id, resolved_at, resolved_by_user_id, parent_id) FROM stdin;
\.


--
-- Data for Name: goal_links; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.goal_links (tenant_id, child_goal_id, parent_goal_id, created_at) FROM stdin;
\.


--
-- Data for Name: goal_shares; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.goal_shares (goal_id, team_id, weight, sort_order, created_at, updated_at, tenant_id) FROM stdin;
\.


--
-- Data for Name: goals; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.goals (id, team_id, title, description, priority, weight, work_type, focus_type, owner_text, created_at, updated_at, sort_order, period_id, owner_udids, tenant_id) FROM stdin;
1	1	Fixture goal		P1	100	Delivery	STABILITY		2026-10-08 13:10:37.695768+00	2026-10-08 13:10:37.695768+00	1	1	\N	1
\.


--
-- Data for Name: key_result_notes; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.key_result_notes (key_result_id, text, author_user_id, updated_at, tenant_id) FROM stdin;
\.


--
-- Data for Name: key_results; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.key_results (id, goal_id, title, description, weight, kind, created_at, updated_at, sort_order, progress_updated_at, unit, start_value, target_value, current_value, checkpoints, zeroing_criteria, tenant_id, health_status) FROM stdin;
1	1	linear		30	NUMERICAL	2026-10-08 13:10:37.699142+00	2026-10-08 13:10:37.699142+00	1	\N	%	10	5	7	\N		1	not_started
2	1	percent		30	NUMERICAL	2026-10-08 13:10:37.699142+00	2026-10-08 13:10:37.699142+00	2	\N	%	100	180	150	[{"value": 150, "progress_percent": 50}, {"value": 180, "progress_percent": 100}]		1	not_started
4	1	missing meta		20	NUMERICAL	2026-10-08 13:10:37.699142+00	2026-10-08 13:10:37.699142+00	4	\N	%	0	100	0	\N		1	not_started
3	1	boolean		20	BOOLEAN	2026-10-08 13:10:37.699142+00	2026-10-08 13:10:37.699142+00	3	\N	\N	\N	\N	\N	\N		1	done
\.


--
-- Data for Name: kr_boolean_meta; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.kr_boolean_meta (key_result_id, is_done) FROM stdin;
3	t
\.


--
-- Data for Name: kr_project_stages; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.kr_project_stages (id, key_result_id, title, weight, is_done, sort_order) FROM stdin;
\.


--
-- Data for Name: memberships; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.memberships (id, user_id, tenant_id, role, status, created_at, created_by_user_id) FROM stdin;
1	1	1	user	active	2026-10-08 13:10:37.936827+00	\N
2	2	1	user	active	2026-10-08 13:10:37.936827+00	\N
\.


--
-- Data for Name: notification_channels; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.notification_channels (tenant_id, channel, enabled, config_json, secret_enc, secret_hint, updated_at, updated_by_user_id, default_on) FROM stdin;
\.


--
-- Data for Name: notification_identities; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.notification_identities (tenant_id, user_id, channel, external_id, external_username, linked_at) FROM stdin;
\.


--
-- Data for Name: notification_preferences; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.notification_preferences (tenant_id, user_id, type, enabled, scope, channel_overrides) FROM stdin;
1	1	goal_changed	f	\N	{}
\.


--
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.notifications (id, tenant_id, user_id, type, kind, actor_user_id, team_id, period_id, goal_id, kr_id, comment_id, entity_title, payload_json, coalesce_key, coalesce_count, created_at, updated_at, read_at) FROM stdin;
1	1	1	goal_changed	goal_changed	2	\N	\N	1	\N	\N		{"preserve": true}	migration-fixture	1	2026-10-08 13:10:39.135712+00	2026-10-08 13:10:39.135712+00	\N
\.


--
-- Data for Name: periods; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.periods (id, name, start_date, end_date, created_at, updated_at, tenant_id, archived_at) FROM stdin;
1	Fixture	2024-01-01	2024-03-31	2026-10-08 13:10:37.693007+00	2026-10-08 13:10:37.693007+00	1	\N
\.


--
-- Data for Name: schema_migrations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.schema_migrations (version, dirty) FROM stdin;
49	f
\.


--
-- Data for Name: system_settings; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.system_settings (key, value_json) FROM stdin;
\.


--
-- Data for Name: team_period_progress_snapshots; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.team_period_progress_snapshots (id, tenant_id, period_id, team_id, snapshot_date, progress, created_at) FROM stdin;
\.


--
-- Data for Name: team_period_statuses; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.team_period_statuses (team_id, period_id, status, updated_at, tenant_id) FROM stdin;
\.


--
-- Data for Name: teams; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.teams (id, name, created_at, updated_at, team_type, parent_id, lead, description, deleted_at, lead_udid, tenant_id) FROM stdin;
1	migration-fixture	2026-10-08 13:10:37.689755+00	2026-10-08 13:10:37.689755+00	team	\N			\N	\N	1
\.


--
-- Data for Name: tenant_invitations; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tenant_invitations (id, tenant_id, email, role, token_hash, status, created_by_user_id, created_at, expires_at, max_uses, use_count) FROM stdin;
\.


--
-- Data for Name: tenant_settings; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tenant_settings (tenant_id, key, value_json) FROM stdin;
1	new_user_policy	"empty"
1	default_hierarchy_node_id	null
\.


--
-- Data for Name: tenants; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.tenants (id, slug, name, status, created_at, deleted_at) FROM stdin;
1	default	Default	active	2026-10-08 13:10:37.877945+00	\N
\.


--
-- Data for Name: user_hierarchy_grants; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.user_hierarchy_grants (id, user_id, team_id, created_at, created_by_user_id, tenant_id) FROM stdin;
\.


--
-- Data for Name: user_settings; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.user_settings (user_id, key, value_json) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users (id, provider_subject_key, provider, subject, display_name, avatar_url, email, attributes_json, created_at, updated_at, last_login_at, udid, is_system_admin) FROM stdin;
1	system:anonymous-local	system	anonymous-local	Anonymous		\N	{}	2026-10-08 13:10:37.105605+00	2026-10-08 13:10:37.105605+00	2026-10-08 13:10:37.105605+00	5237a657-2d4a-44c1-ad8e-fdb101f4e1cc	f
2	system:migration	system	migration	Migration		\N	{}	2026-10-08 13:10:37.105605+00	2026-10-08 13:10:37.105605+00	2026-10-08 13:10:37.105605+00	10a08f56-0361-4798-b714-afa1be0aeeac	f
\.


--
-- Name: activity_events_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.activity_events_id_seq', 1, false);


--
-- Name: goal_comments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.goal_comments_id_seq', 1, false);


--
-- Name: goals_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.goals_id_seq', 1, true);


--
-- Name: key_results_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.key_results_id_seq', 4, true);


--
-- Name: kr_project_stages_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.kr_project_stages_id_seq', 1, false);


--
-- Name: memberships_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.memberships_id_seq', 2, true);


--
-- Name: notifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.notifications_id_seq', 1, true);


--
-- Name: periods_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.periods_id_seq', 1, true);


--
-- Name: team_period_progress_snapshots_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.team_period_progress_snapshots_id_seq', 1, false);


--
-- Name: teams_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.teams_id_seq', 1, true);


--
-- Name: tenant_invitations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.tenant_invitations_id_seq', 1, false);


--
-- Name: tenants_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.tenants_id_seq', 1, true);


--
-- Name: user_hierarchy_grants_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.user_hierarchy_grants_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 100, true);


--
-- Name: activity_events activity_events_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity_events
    ADD CONSTRAINT activity_events_pkey PRIMARY KEY (id);


--
-- Name: auth_sessions auth_sessions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_sessions
    ADD CONSTRAINT auth_sessions_pkey PRIMARY KEY (id);


--
-- Name: goal_comments goal_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goal_comments
    ADD CONSTRAINT goal_comments_pkey PRIMARY KEY (id);


--
-- Name: goal_links goal_links_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goal_links
    ADD CONSTRAINT goal_links_pkey PRIMARY KEY (tenant_id, child_goal_id, parent_goal_id);


--
-- Name: goal_shares goal_shares_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goal_shares
    ADD CONSTRAINT goal_shares_pkey PRIMARY KEY (goal_id, team_id);


--
-- Name: goals goals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_pkey PRIMARY KEY (id);


--
-- Name: key_result_notes key_result_notes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.key_result_notes
    ADD CONSTRAINT key_result_notes_pkey PRIMARY KEY (key_result_id);


--
-- Name: key_results key_results_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.key_results
    ADD CONSTRAINT key_results_pkey PRIMARY KEY (id);


--
-- Name: kr_boolean_meta kr_boolean_meta_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kr_boolean_meta
    ADD CONSTRAINT kr_boolean_meta_pkey PRIMARY KEY (key_result_id);


--
-- Name: kr_project_stages kr_project_stages_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kr_project_stages
    ADD CONSTRAINT kr_project_stages_pkey PRIMARY KEY (id);


--
-- Name: memberships memberships_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memberships
    ADD CONSTRAINT memberships_pkey PRIMARY KEY (id);


--
-- Name: memberships memberships_user_id_tenant_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memberships
    ADD CONSTRAINT memberships_user_id_tenant_id_key UNIQUE (user_id, tenant_id);


--
-- Name: notification_channels notification_channels_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_channels
    ADD CONSTRAINT notification_channels_pkey PRIMARY KEY (tenant_id, channel);


--
-- Name: notification_identities notification_identities_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_identities
    ADD CONSTRAINT notification_identities_pkey PRIMARY KEY (tenant_id, user_id, channel);


--
-- Name: notification_identities notification_identities_tenant_id_channel_external_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_identities
    ADD CONSTRAINT notification_identities_tenant_id_channel_external_id_key UNIQUE (tenant_id, channel, external_id);


--
-- Name: notification_preferences notification_preferences_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_preferences
    ADD CONSTRAINT notification_preferences_pkey PRIMARY KEY (tenant_id, user_id, type);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_tenant_id_user_id_coalesce_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_tenant_id_user_id_coalesce_key_key UNIQUE (tenant_id, user_id, coalesce_key);


--
-- Name: periods periods_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.periods
    ADD CONSTRAINT periods_pkey PRIMARY KEY (id);


--
-- Name: periods periods_tenant_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.periods
    ADD CONSTRAINT periods_tenant_name_key UNIQUE (tenant_id, name);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: system_settings system_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.system_settings
    ADD CONSTRAINT system_settings_pkey PRIMARY KEY (key);


--
-- Name: team_period_progress_snapshots team_period_progress_snapshot_tenant_id_period_id_team_id_s_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_period_progress_snapshots
    ADD CONSTRAINT team_period_progress_snapshot_tenant_id_period_id_team_id_s_key UNIQUE (tenant_id, period_id, team_id, snapshot_date);


--
-- Name: team_period_progress_snapshots team_period_progress_snapshots_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_period_progress_snapshots
    ADD CONSTRAINT team_period_progress_snapshots_pkey PRIMARY KEY (id);


--
-- Name: team_period_statuses team_period_statuses_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_period_statuses
    ADD CONSTRAINT team_period_statuses_pkey PRIMARY KEY (team_id, period_id);


--
-- Name: teams teams_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_pkey PRIMARY KEY (id);


--
-- Name: tenant_invitations tenant_invitations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant_invitations
    ADD CONSTRAINT tenant_invitations_pkey PRIMARY KEY (id);


--
-- Name: tenant_settings tenant_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant_settings
    ADD CONSTRAINT tenant_settings_pkey PRIMARY KEY (tenant_id, key);


--
-- Name: tenants tenants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT tenants_pkey PRIMARY KEY (id);


--
-- Name: tenants tenants_slug_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenants
    ADD CONSTRAINT tenants_slug_key UNIQUE (slug);


--
-- Name: user_hierarchy_grants user_hierarchy_grants_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_hierarchy_grants
    ADD CONSTRAINT user_hierarchy_grants_pkey PRIMARY KEY (id);


--
-- Name: user_hierarchy_grants user_hierarchy_grants_user_id_team_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_hierarchy_grants
    ADD CONSTRAINT user_hierarchy_grants_user_id_team_id_key UNIQUE (user_id, team_id);


--
-- Name: user_settings user_settings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_settings
    ADD CONSTRAINT user_settings_pkey PRIMARY KEY (user_id, key);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_provider_subject_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_provider_subject_key_key UNIQUE (provider_subject_key);


--
-- Name: auth_sessions_expires_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_sessions_expires_at_idx ON public.auth_sessions USING btree (expires_at);


--
-- Name: auth_sessions_user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_sessions_user_id_idx ON public.auth_sessions USING btree (user_id);


--
-- Name: goal_shares_team_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX goal_shares_team_idx ON public.goal_shares USING btree (team_id);


--
-- Name: goals_team_period_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX goals_team_period_idx ON public.goals USING btree (team_id, period_id);


--
-- Name: goals_team_period_sort_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX goals_team_period_sort_idx ON public.goals USING btree (team_id, period_id, sort_order);


--
-- Name: idx_activity_events_goal; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_activity_events_goal ON public.activity_events USING btree (goal_id);


--
-- Name: idx_activity_events_tenant_actor; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_activity_events_tenant_actor ON public.activity_events USING btree (tenant_id, actor_user_id);


--
-- Name: idx_activity_events_tenant_created; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_activity_events_tenant_created ON public.activity_events USING btree (tenant_id, created_at DESC, id DESC);


--
-- Name: idx_activity_events_tenant_period; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_activity_events_tenant_period ON public.activity_events USING btree (tenant_id, period_id, created_at DESC);


--
-- Name: idx_activity_events_tenant_team; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_activity_events_tenant_team ON public.activity_events USING btree (tenant_id, team_id, created_at DESC);


--
-- Name: idx_goal_comments_parent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_goal_comments_parent ON public.goal_comments USING btree (goal_id, parent_id, created_at);


--
-- Name: idx_goal_comments_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_goal_comments_tenant ON public.goal_comments USING btree (tenant_id);


--
-- Name: idx_goal_links_child; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_goal_links_child ON public.goal_links USING btree (tenant_id, child_goal_id);


--
-- Name: idx_goal_links_parent; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_goal_links_parent ON public.goal_links USING btree (tenant_id, parent_goal_id);


--
-- Name: idx_goal_shares_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_goal_shares_tenant ON public.goal_shares USING btree (tenant_id);


--
-- Name: idx_goals_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_goals_tenant ON public.goals USING btree (tenant_id);


--
-- Name: idx_key_result_notes_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_key_result_notes_tenant ON public.key_result_notes USING btree (tenant_id);


--
-- Name: idx_key_results_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_key_results_tenant ON public.key_results USING btree (tenant_id);


--
-- Name: idx_notifications_feed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_feed ON public.notifications USING btree (tenant_id, user_id, created_at DESC, id DESC);


--
-- Name: idx_notifications_unread; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_unread ON public.notifications USING btree (tenant_id, user_id) WHERE (read_at IS NULL);


--
-- Name: idx_notifications_updated; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_notifications_updated ON public.notifications USING btree (updated_at);


--
-- Name: idx_periods_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_periods_tenant ON public.periods USING btree (tenant_id);


--
-- Name: idx_team_period_statuses_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_team_period_statuses_tenant ON public.team_period_statuses USING btree (tenant_id);


--
-- Name: idx_teams_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_teams_tenant ON public.teams USING btree (tenant_id);


--
-- Name: idx_tenant_invitations_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tenant_invitations_tenant ON public.tenant_invitations USING btree (tenant_id);


--
-- Name: idx_tpps_tenant_period_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_tpps_tenant_period_date ON public.team_period_progress_snapshots USING btree (tenant_id, period_id, snapshot_date);


--
-- Name: idx_user_hierarchy_grants_tenant; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_hierarchy_grants_tenant ON public.user_hierarchy_grants USING btree (tenant_id);


--
-- Name: key_results_goal_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX key_results_goal_idx ON public.key_results USING btree (goal_id);


--
-- Name: key_results_goal_sort_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX key_results_goal_sort_idx ON public.key_results USING btree (goal_id, sort_order);


--
-- Name: key_results_progress_updated_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX key_results_progress_updated_at_idx ON public.key_results USING btree (progress_updated_at);


--
-- Name: teams_deleted_at_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX teams_deleted_at_idx ON public.teams USING btree (deleted_at);


--
-- Name: teams_lead_udid_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX teams_lead_udid_idx ON public.teams USING btree (lead_udid);


--
-- Name: teams_parent_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX teams_parent_id_idx ON public.teams USING btree (parent_id);


--
-- Name: user_hierarchy_grants_user_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX user_hierarchy_grants_user_id_idx ON public.user_hierarchy_grants USING btree (user_id);


--
-- Name: users_provider_subject_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX users_provider_subject_idx ON public.users USING btree (provider, subject);


--
-- Name: users_udid_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX users_udid_idx ON public.users USING btree (udid);


--
-- Name: activity_events activity_events_actor_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity_events
    ADD CONSTRAINT activity_events_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES public.users(id);


--
-- Name: activity_events activity_events_period_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity_events
    ADD CONSTRAINT activity_events_period_id_fkey FOREIGN KEY (period_id) REFERENCES public.periods(id) ON DELETE SET NULL;


--
-- Name: activity_events activity_events_team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity_events
    ADD CONSTRAINT activity_events_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE SET NULL;


--
-- Name: activity_events activity_events_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.activity_events
    ADD CONSTRAINT activity_events_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: auth_sessions auth_sessions_active_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_sessions
    ADD CONSTRAINT auth_sessions_active_tenant_id_fkey FOREIGN KEY (active_tenant_id) REFERENCES public.tenants(id);


--
-- Name: auth_sessions auth_sessions_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_sessions
    ADD CONSTRAINT auth_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: goal_comments goal_comments_author_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goal_comments
    ADD CONSTRAINT goal_comments_author_user_id_fkey FOREIGN KEY (author_user_id) REFERENCES public.users(id);


--
-- Name: goal_comments goal_comments_goal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goal_comments
    ADD CONSTRAINT goal_comments_goal_id_fkey FOREIGN KEY (goal_id) REFERENCES public.goals(id) ON DELETE CASCADE;


--
-- Name: goal_comments goal_comments_parent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goal_comments
    ADD CONSTRAINT goal_comments_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.goal_comments(id) ON DELETE CASCADE;


--
-- Name: goal_comments goal_comments_resolved_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goal_comments
    ADD CONSTRAINT goal_comments_resolved_by_user_id_fkey FOREIGN KEY (resolved_by_user_id) REFERENCES public.users(id);


--
-- Name: goal_comments goal_comments_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goal_comments
    ADD CONSTRAINT goal_comments_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: goal_links goal_links_child_goal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goal_links
    ADD CONSTRAINT goal_links_child_goal_id_fkey FOREIGN KEY (child_goal_id) REFERENCES public.goals(id) ON DELETE CASCADE;


--
-- Name: goal_links goal_links_parent_goal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goal_links
    ADD CONSTRAINT goal_links_parent_goal_id_fkey FOREIGN KEY (parent_goal_id) REFERENCES public.goals(id) ON DELETE CASCADE;


--
-- Name: goal_links goal_links_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goal_links
    ADD CONSTRAINT goal_links_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: goal_shares goal_shares_goal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goal_shares
    ADD CONSTRAINT goal_shares_goal_id_fkey FOREIGN KEY (goal_id) REFERENCES public.goals(id) ON DELETE CASCADE;


--
-- Name: goal_shares goal_shares_team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goal_shares
    ADD CONSTRAINT goal_shares_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE CASCADE;


--
-- Name: goal_shares goal_shares_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goal_shares
    ADD CONSTRAINT goal_shares_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: goals goals_period_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_period_fk FOREIGN KEY (period_id) REFERENCES public.periods(id) ON DELETE CASCADE;


--
-- Name: goals goals_team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE CASCADE;


--
-- Name: goals goals_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.goals
    ADD CONSTRAINT goals_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: key_result_notes key_result_notes_author_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.key_result_notes
    ADD CONSTRAINT key_result_notes_author_user_id_fkey FOREIGN KEY (author_user_id) REFERENCES public.users(id);


--
-- Name: key_result_notes key_result_notes_key_result_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.key_result_notes
    ADD CONSTRAINT key_result_notes_key_result_id_fkey FOREIGN KEY (key_result_id) REFERENCES public.key_results(id) ON DELETE CASCADE;


--
-- Name: key_result_notes key_result_notes_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.key_result_notes
    ADD CONSTRAINT key_result_notes_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: key_results key_results_goal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.key_results
    ADD CONSTRAINT key_results_goal_id_fkey FOREIGN KEY (goal_id) REFERENCES public.goals(id) ON DELETE CASCADE;


--
-- Name: key_results key_results_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.key_results
    ADD CONSTRAINT key_results_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: kr_boolean_meta kr_boolean_meta_key_result_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kr_boolean_meta
    ADD CONSTRAINT kr_boolean_meta_key_result_id_fkey FOREIGN KEY (key_result_id) REFERENCES public.key_results(id) ON DELETE CASCADE;


--
-- Name: kr_project_stages kr_project_stages_key_result_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kr_project_stages
    ADD CONSTRAINT kr_project_stages_key_result_id_fkey FOREIGN KEY (key_result_id) REFERENCES public.key_results(id) ON DELETE CASCADE;


--
-- Name: memberships memberships_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memberships
    ADD CONSTRAINT memberships_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: memberships memberships_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memberships
    ADD CONSTRAINT memberships_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: memberships memberships_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.memberships
    ADD CONSTRAINT memberships_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: notification_channels notification_channels_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_channels
    ADD CONSTRAINT notification_channels_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: notification_channels notification_channels_updated_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_channels
    ADD CONSTRAINT notification_channels_updated_by_user_id_fkey FOREIGN KEY (updated_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: notification_identities notification_identities_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_identities
    ADD CONSTRAINT notification_identities_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: notification_identities notification_identities_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_identities
    ADD CONSTRAINT notification_identities_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: notification_preferences notification_preferences_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_preferences
    ADD CONSTRAINT notification_preferences_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: notification_preferences notification_preferences_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_preferences
    ADD CONSTRAINT notification_preferences_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: notifications notifications_actor_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_actor_user_id_fkey FOREIGN KEY (actor_user_id) REFERENCES public.users(id);


--
-- Name: notifications notifications_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: notifications notifications_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: periods periods_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.periods
    ADD CONSTRAINT periods_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: team_period_progress_snapshots team_period_progress_snapshots_period_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_period_progress_snapshots
    ADD CONSTRAINT team_period_progress_snapshots_period_id_fkey FOREIGN KEY (period_id) REFERENCES public.periods(id) ON DELETE CASCADE;


--
-- Name: team_period_progress_snapshots team_period_progress_snapshots_team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_period_progress_snapshots
    ADD CONSTRAINT team_period_progress_snapshots_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE CASCADE;


--
-- Name: team_period_progress_snapshots team_period_progress_snapshots_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_period_progress_snapshots
    ADD CONSTRAINT team_period_progress_snapshots_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: team_period_statuses team_period_statuses_period_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_period_statuses
    ADD CONSTRAINT team_period_statuses_period_id_fkey FOREIGN KEY (period_id) REFERENCES public.periods(id) ON DELETE CASCADE;


--
-- Name: team_period_statuses team_period_statuses_team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_period_statuses
    ADD CONSTRAINT team_period_statuses_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE CASCADE;


--
-- Name: team_period_statuses team_period_statuses_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team_period_statuses
    ADD CONSTRAINT team_period_statuses_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: teams teams_lead_udid_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_lead_udid_fkey FOREIGN KEY (lead_udid) REFERENCES public.users(udid) ON DELETE SET NULL;


--
-- Name: teams teams_parent_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES public.teams(id) ON DELETE SET NULL;


--
-- Name: teams teams_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teams
    ADD CONSTRAINT teams_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: tenant_invitations tenant_invitations_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant_invitations
    ADD CONSTRAINT tenant_invitations_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: tenant_invitations tenant_invitations_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant_invitations
    ADD CONSTRAINT tenant_invitations_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: tenant_settings tenant_settings_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.tenant_settings
    ADD CONSTRAINT tenant_settings_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id) ON DELETE CASCADE;


--
-- Name: user_hierarchy_grants user_hierarchy_grants_created_by_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_hierarchy_grants
    ADD CONSTRAINT user_hierarchy_grants_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES public.users(id);


--
-- Name: user_hierarchy_grants user_hierarchy_grants_team_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_hierarchy_grants
    ADD CONSTRAINT user_hierarchy_grants_team_id_fkey FOREIGN KEY (team_id) REFERENCES public.teams(id) ON DELETE CASCADE;


--
-- Name: user_hierarchy_grants user_hierarchy_grants_tenant_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_hierarchy_grants
    ADD CONSTRAINT user_hierarchy_grants_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenants(id);


--
-- Name: user_hierarchy_grants user_hierarchy_grants_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_hierarchy_grants
    ADD CONSTRAINT user_hierarchy_grants_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: user_settings user_settings_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_settings
    ADD CONSTRAINT user_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict zArFcmtINrh3EjUASKPkJcZoW2PQoRdheicuSkAzTJDS2e3vm7bIODQHZ35PTZY

